spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3366/crm?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: password
  application:
    name: crmsys
  devtools:
    restart:
      enabled: true
server:
  port: 9527